name: patterns
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <3.19.0'

dependencies:
  faker: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  effective_dart: ^1.3.2
  extra_pedantic: ^3.0.0
  purple_lints: ^0.3.0
  flutter_lints: ^2.0.1
  lint: ^1.10.0